### ISSUE TITLE
Already Signed

### ISSUE THREAD

**Issue by GabikaPasta** [zeroequalsone/Sign#1]
Can you make players can't sign an item that was already signed

**Comment by zeroequalsone** [comment]
**If you downloaded the source, you can just go into the Command_Sign class and change this:**

https://www.toptal.com/developers/hastebin/ujimixixik.csharp
				
**to this:**

https://www.toptal.com/developers/hastebin/oyuvevulus.csharp

**Comment by zeroequalsone** [comment]
No need to anymore. I've updated the plugin. You can now select if you want this option to be enabled in the config and as well change the message if you want to.

**Comment by GabikaPasta** [comment]
thank you! :)
